--  SPDX-License-Identifier: Apache-2.0
--
--  Copyright (c) 2012 Felix Krause <contact@flyx.org>
--
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.

package GL.Enums.Getter is
   pragma Preelaborate;

   type Parameter is
     (Line_Smooth,
      Polygon_Mode,
      Polygon_Smooth,
      Cull_Face,
      Cull_Face_Mode,
      Front_Face,
      Depth_Range,
      Depth_Test,
      Depth_Writemask,
      Depth_Clear_Value,
      Depth_Func,
      Stencil_Test,
      Stencil_Clear_Value,
      Stencil_Func,
      Stencil_Value_Mask,
      Stencil_Fail,
      Stencil_Pass_Depth_Fail,
      Stencil_Pass_Depth_Pass,
      Stencil_Ref,
      Stencil_Writemask,
      Viewport,
      Dither,
      Blend_Dst,
      Blend_Src,
      Blend,
      Logic_Op_Mode,
      Color_Logic_Op,
      Draw_Buffer,
      Read_Buffer,
      Scissor_Box,
      Scissor_Test,
      Color_Clear_Value,
      Color_Writemask,
      Doublebuffer,
      Stereo,
      Line_Smooth_Hint,
      Polygon_Smooth_Hint,
      Unpack_Alignment,
      Pack_Alignment,
      Max_Clip_Distances,
      Max_Texture_Size,
      Max_Viewport_Dims,
      Subpixel_Bits,
      Texture_1D,
      Texture_2D,
      Polygon_Offset_Units,
      Blend_Color,
      Blend_Equation_RGB,
      Polygon_Offset_Factor,
      Blend_Dst_RGB,
      Blend_Src_RGB,
      Blend_Dst_Alpha,
      Blend_Src_Alpha,
      Major_Version,
      Minor_Version,
      Num_Extensions,
      Max_Viewports,
      Viewport_Subpixel_Bits,
      Viewport_Bounds_Range,
      Max_Compute_Shared_Memory_Size,
      Num_Shading_Language_Versions,
      Active_Texture,
      Max_Texture_Max_Anisotropy,
      Stencil_Back_Func,
      Stencil_Back_Fail,
      Stencil_Back_Pass_Depth_Fail,
      Stencil_Back_Pass_Depth_Pass,
      Blend_Equation_Alpha,
      Max_Texture_Image_Units,
      Max_Vertex_Texture_Image_Units,
      Max_Combined_Texture_Image_Units,
      Max_Geometry_Texture_Image_Units,
      Min_Sample_Shading_Value,
      Stencil_Back_Ref,
      Stencil_Back_Value_Mask,
      Stencil_Back_Writemask,
      Polygon_Offset_Clamp,
      Timestamp,
      Max_Tess_Control_Texture_Image_Units,
      Max_Tess_Evaluation_Texture_Image_Units,
      Min_Map_Buffer_Alignment,
      Max_Compute_Work_Group_Invocations,
      Unpack_Compressed_Block_Width,
      Unpack_Compressed_Block_Height,
      Unpack_Compressed_Block_Depth,
      Unpack_Compressed_Block_Size,
      Pack_Compressed_Block_Width,
      Pack_Compressed_Block_Height,
      Pack_Compressed_Block_Depth,
      Pack_Compressed_Block_Size,
      Max_Debug_Message_Length,
      Debug_Logged_Messages,
      Max_Compute_Texture_Image_Units,
      Max_Compute_Work_Group_Count,
      Max_Compute_Work_Group_Size,
      Max_Framebuffer_Width,
      Max_Framebuffer_Height,
      Max_Framebuffer_Layers,
      Max_Framebuffer_Samples,
      Clip_Origin,
      Clip_Depth_Mode);

   type String_Parameter is
     (Vendor, Renderer, Version, Extensions, Shading_Language_Version);

private

   for Parameter use
     (Line_Smooth                   => 16#0B20#,
      Polygon_Mode                  => 16#0B40#,
      Polygon_Smooth                => 16#0B41#,
      Cull_Face                     => 16#0B44#,
      Cull_Face_Mode                => 16#0B45#,
      Front_Face                    => 16#0B46#,
      Depth_Range                   => 16#0B70#,
      Depth_Test                    => 16#0B71#,
      Depth_Writemask               => 16#0B72#,
      Depth_Clear_Value             => 16#0B73#,
      Depth_Func                    => 16#0B74#,
      Stencil_Test                  => 16#0B90#,
      Stencil_Clear_Value           => 16#0B91#,
      Stencil_Func                  => 16#0B92#,
      Stencil_Value_Mask            => 16#0B93#,
      Stencil_Fail                  => 16#0B94#,
      Stencil_Pass_Depth_Fail       => 16#0B95#,
      Stencil_Pass_Depth_Pass       => 16#0B96#,
      Stencil_Ref                   => 16#0B97#,
      Stencil_Writemask             => 16#0B98#,
      Viewport                      => 16#0BA2#,
      Dither                        => 16#0BD0#,
      Blend_Dst                     => 16#0BE0#,
      Blend_Src                     => 16#0BE1#,
      Blend                         => 16#0BE2#,
      Logic_Op_Mode                 => 16#0BF0#,
      Color_Logic_Op                => 16#0BF2#,
      Draw_Buffer                   => 16#0C01#,
      Read_Buffer                   => 16#0C02#,
      Scissor_Box                   => 16#0C10#,
      Scissor_Test                  => 16#0C11#,
      Color_Clear_Value             => 16#0C22#,
      Color_Writemask               => 16#0C23#,
      Doublebuffer                  => 16#0C32#,
      Stereo                        => 16#0C33#,
      Line_Smooth_Hint              => 16#0C52#,
      Polygon_Smooth_Hint           => 16#0C53#,
      Unpack_Alignment              => 16#0CF5#,
      Pack_Alignment                => 16#0D05#,
      Max_Clip_Distances            => 16#0D32#,
      Max_Texture_Size              => 16#0D33#,
      Max_Viewport_Dims             => 16#0D3A#,
      Subpixel_Bits                 => 16#0D50#,
      Texture_1D                    => 16#0DE0#,
      Texture_2D                    => 16#0DE1#,
      Polygon_Offset_Units          => 16#2A00#,
      Blend_Color                   => 16#8005#,
      Blend_Equation_RGB            => 16#8009#,
      Polygon_Offset_Factor         => 16#8038#,
      Blend_Dst_RGB                 => 16#80C8#,
      Blend_Src_RGB                 => 16#80C9#,
      Blend_Dst_Alpha               => 16#80CA#,
      Blend_Src_Alpha               => 16#80CB#,
      Major_Version                 => 16#821B#,
      Minor_Version                 => 16#821C#,
      Num_Extensions                => 16#821D#,
      Max_Viewports                 => 16#825B#,
      Viewport_Subpixel_Bits        => 16#825C#,
      Viewport_Bounds_Range         => 16#825D#,
      Max_Compute_Shared_Memory_Size => 16#8262#,
      Num_Shading_Language_Versions => 16#82E9#,
      Active_Texture                => 16#84E0#,
      Max_Texture_Max_Anisotropy    => 16#84FF#,
      Stencil_Back_Func             => 16#8800#,
      Stencil_Back_Fail             => 16#8801#,
      Stencil_Back_Pass_Depth_Fail  => 16#8802#,
      Stencil_Back_Pass_Depth_Pass  => 16#8803#,
      Blend_Equation_Alpha          => 16#883D#,
      Max_Texture_Image_Units          => 16#8872#,
      Max_Vertex_Texture_Image_Units   => 16#8B4C#,
      Max_Combined_Texture_Image_Units => 16#8B4D#,
      Max_Geometry_Texture_Image_Units => 16#8C29#,
      Min_Sample_Shading_Value      => 16#8C37#,
      Stencil_Back_Ref              => 16#8CA3#,
      Stencil_Back_Value_Mask       => 16#8CA4#,
      Stencil_Back_Writemask        => 16#8CA5#,
      Polygon_Offset_Clamp          => 16#8E1B#,
      Timestamp                     => 16#8E28#,
      Max_Tess_Control_Texture_Image_Units    => 16#8E81#,
      Max_Tess_Evaluation_Texture_Image_Units => 16#8E82#,
      Min_Map_Buffer_Alignment      => 16#90BC#,
      Max_Compute_Work_Group_Invocations => 16#90EB#,
      Unpack_Compressed_Block_Width  => 16#9127#,
      Unpack_Compressed_Block_Height => 16#9128#,
      Unpack_Compressed_Block_Depth  => 16#9129#,
      Unpack_Compressed_Block_Size   => 16#912A#,
      Pack_Compressed_Block_Width    => 16#912B#,
      Pack_Compressed_Block_Height   => 16#912C#,
      Pack_Compressed_Block_Depth    => 16#912D#,
      Pack_Compressed_Block_Size     => 16#912E#,
      Max_Debug_Message_Length      => 16#9143#,
      Debug_Logged_Messages         => 16#9145#,
      Max_Compute_Texture_Image_Units => 16#91BC#,
      Max_Compute_Work_Group_Count  => 16#91BE#,
      Max_Compute_Work_Group_Size   => 16#91BF#,
      Max_Framebuffer_Width         => 16#9315#,
      Max_Framebuffer_Height        => 16#9316#,
      Max_Framebuffer_Layers        => 16#9317#,
      Max_Framebuffer_Samples       => 16#9318#,
      Clip_Origin                   => 16#935C#,
      Clip_Depth_Mode               => 16#935D#);
   for Parameter'Size use Low_Level.Enum'Size;

   for String_Parameter use
     (Vendor                   => 16#1F00#,
      Renderer                 => 16#1F01#,
      Version                  => 16#1F02#,
      Extensions               => 16#1F03#,
      Shading_Language_Version => 16#8B8C#);
   for String_Parameter'Size use Low_Level.Enum'Size;

end GL.Enums.Getter;
