--  SPDX-License-Identifier: Apache-2.0
--
--  Copyright (c) 2018 onox <denkpadje@gmail.com>
--
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.

package GL.Enums.Internalformat is
   pragma Preelaborate;

   type Parameter is
     (Samples,
      Internalformat_Supported,
      Internalformat_Preferred,
      Internalformat_Red_Size,
      Internalformat_Green_Size,
      Internalformat_Blue_Size,
      Internalformat_Alpha_Size,
      Internalformat_Depth_Size,
      Internalformat_Stencil_Size,
      Internalformat_Shared_Size,
      Internalformat_Red_Type,
      Internalformat_Green_Type,
      Internalformat_Blue_Type,
      Internalformat_Alpha_Type,
      Internalformat_Depth_Type,
      Internalformat_Stencil_Type,
      Max_Width,
      Max_Height,
      Max_Depth,
      Max_Layers,
      Max_Combined_Dimensions,
      Color_Components,
      Depth_Components,
      Stencil_Components,
      Color_Renderable,
      Depth_Renderable,
      Stencil_Renderable,
      Framebuffer_Renderable,
      Framebuffer_Renderable_Layered,
      Framebuffer_Blend,
      Texture_Image_Format,
      Texture_Image_Type,
      Get_Texture_Image_Format,
      Get_Texture_Image_Type,
      Mipmap,
      Manual_Generate_Mipmap,
      Auto_Generate_Mipmap,
      Color_Encoding,
      sRGB_Read,
      sRGB_Write,
      sRGB_Decode_ARB,
      Filter,
      Vertex_Texture,
      Tess_Control_Texture,
      Tess_Evaluation_Texture,
      Geometry_Texture,
      Fragment_Texture,
      Compute_Texture,
      Texture_Shadow,
      Texture_Gather,
      Texture_Gather_Shadow,
      Shader_Image_Load,
      Shader_Image_Store,
      Shader_Image_Atomic,
      Image_Texel_Size,
      Image_Compatibility_Class,
      Image_Pixel_Format,
      Image_Pixel_Type,
      Simultaneous_Texture_And_Depth_Test,
      Simultaneous_Texture_And_Stencil_Test,
      Simultaneous_Texture_And_Depth_Write,
      Simultaneous_Texture_And_Stencil_Write,
      Texture_Compressed_Block_Width,
      Texture_Compressed_Block_Height,
      Texture_Compressed_Block_Size,
      Clear_Buffer,
      Texture_View,
      View_Compatibility_Class,
      Texture_Compressed,
      Image_Format_Compatibility_Type,
      Num_Sample_Counts);

private

   for Parameter use
     (Samples                                => 16#80A9#,
      Internalformat_Supported               => 16#826F#,
      Internalformat_Preferred               => 16#8270#,
      Internalformat_Red_Size                => 16#8271#,
      Internalformat_Green_Size              => 16#8272#,
      Internalformat_Blue_Size               => 16#8273#,
      Internalformat_Alpha_Size              => 16#8274#,
      Internalformat_Depth_Size              => 16#8275#,
      Internalformat_Stencil_Size            => 16#8276#,
      Internalformat_Shared_Size             => 16#8277#,
      Internalformat_Red_Type                => 16#8278#,
      Internalformat_Green_Type              => 16#8279#,
      Internalformat_Blue_Type               => 16#827A#,
      Internalformat_Alpha_Type              => 16#827B#,
      Internalformat_Depth_Type              => 16#827C#,
      Internalformat_Stencil_Type            => 16#827D#,
      Max_Width                              => 16#827E#,
      Max_Height                             => 16#827F#,
      Max_Depth                              => 16#8280#,
      Max_Layers                             => 16#8281#,
      Max_Combined_Dimensions                => 16#8282#,
      Color_Components                       => 16#8283#,
      Depth_Components                       => 16#8284#,
      Stencil_Components                     => 16#8285#,
      Color_Renderable                       => 16#8286#,
      Depth_Renderable                       => 16#8287#,
      Stencil_Renderable                     => 16#8288#,
      Framebuffer_Renderable                 => 16#8289#,
      Framebuffer_Renderable_Layered         => 16#828A#,
      Framebuffer_Blend                      => 16#828B#,
      Texture_Image_Format                   => 16#828F#,
      Texture_Image_Type                     => 16#8290#,
      Get_Texture_Image_Format               => 16#8291#,
      Get_Texture_Image_Type                 => 16#8292#,
      Mipmap                                 => 16#8293#,
      Manual_Generate_Mipmap                 => 16#8294#,
      Auto_Generate_Mipmap                   => 16#8295#,
      Color_Encoding                         => 16#8296#,
      sRGB_Read                              => 16#8297#,
      sRGB_Write                             => 16#8298#,
      sRGB_Decode_ARB                        => 16#8299#,
      Filter                                 => 16#829A#,
      Vertex_Texture                         => 16#829B#,
      Tess_Control_Texture                   => 16#829C#,
      Tess_Evaluation_Texture                => 16#829D#,
      Geometry_Texture                       => 16#829E#,
      Fragment_Texture                       => 16#829F#,
      Compute_Texture                        => 16#82A0#,
      Texture_Shadow                         => 16#82A1#,
      Texture_Gather                         => 16#82A2#,
      Texture_Gather_Shadow                  => 16#82A3#,
      Shader_Image_Load                      => 16#82A4#,
      Shader_Image_Store                     => 16#82A5#,
      Shader_Image_Atomic                    => 16#82A6#,
      Image_Texel_Size                       => 16#82A7#,
      Image_Compatibility_Class              => 16#82A8#,
      Image_Pixel_Format                     => 16#82A9#,
      Image_Pixel_Type                       => 16#82AA#,
      Simultaneous_Texture_And_Depth_Test    => 16#82AC#,
      Simultaneous_Texture_And_Stencil_Test  => 16#82AD#,
      Simultaneous_Texture_And_Depth_Write   => 16#82AE#,
      Simultaneous_Texture_And_Stencil_Write => 16#82AF#,
      Texture_Compressed_Block_Width         => 16#82B1#,
      Texture_Compressed_Block_Height        => 16#82B2#,
      Texture_Compressed_Block_Size          => 16#82B3#,
      Clear_Buffer                           => 16#82B4#,
      Texture_View                           => 16#82B5#,
      View_Compatibility_Class               => 16#82B6#,
      Texture_Compressed                     => 16#86A1#,
      Image_Format_Compatibility_Type        => 16#90C7#,
      Num_Sample_Counts                      => 16#9380#);
   for Parameter'Size use Low_Level.Enum'Size;

end GL.Enums.Internalformat;
